interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [ "core",
]

[[modules ]]
path = "api"
depends_on = []

[[modules ]]
path = "db"
depends_on = []

[[modules ]]
path = "assets"
depends_on = []

[[modules ]]
path = "ingestion"
depends_on = []

[[modules ]]
path = "config"
depends_on = []

[[modules ]]
path = "utils"
depends_on = []

[[modules ]]
path = "nexus"
depends_on = []
